### ISSUE TITLE
Error while encoding video frame

### ISSUE THREAD

**Issue by epreto** [mesta1/Recording-video-with-c-#1]
Hello,

I'm always having this runtime error:
"Error on _videoSource_NewFrame: Error while encoding video frame"

I have done everything, this only happen in 6th frame, don't know way (even with other input).

Any help?

**Comment by mesta1** [comment]
Is it also happening with the sample url  ? 
http://88.53.197.250/axis-cgi/mjpg/video.cgi?resolution=320×240

**Comment by epreto** [comment]
Curiously it don't happen with sample url or desktop, only with webcam or external device.

**Comment by mesta1** [comment]
what hardware are you using ? USB cam or  IP camera?

**Comment by epreto** [comment]
i'm using my webcam and a external usb video capture device (usb3hdcap)

**Comment by mesta1** [comment]
You can try to comment out some code and see if it resolves.
Just keep
`
 if (_recording)
 {
    _writer.WriteVideoFrame(eventArgs.Frame);
  }
`

**Comment by epreto** [comment]
It simply worked with this! 

Can you explain me why?

**Comment by mesta1** [comment]
It works but you are just adding consecutive images. With the method before you were adding the images with a specified time, so in case of a slow streaming you could reconstruct the timing.
Try also this:

if (_recording)
{
if (_firstFrameTime != null)
{
    _writer.WriteVideoFrame(eventArgs.Frame, DateTime.Now - _firstFrameTime.Value);
}
else
{
   _firstFrameTime = DateTime.Now;
   _writer.WriteVideoFrame(eventArgs.Frame);
}
}

**Comment by epreto** [comment]
Nop, same problem as before...

**Comment by mesta1** [comment]
This commit should fix also this issue:
https://github.com/mesta1/Recording-video-with-c-/commit/c82b2443885a2b5ea71497ddc5bbd358cddef771
