### ISSUE TITLE
Error when select Webcam 

### ISSUE THREAD

**Issue by brian-sj** [mesta1/Recording-video-with-c-#3]
Thank your example.

I have problem with this source. 
Desktop and IPcammera works good.

But when i select webcam,  It make's error.

_```
_   An unhandled exception of type 'System.ArgumentException' occurred in WindowsBase.dll.
     Must create DependencySource on same Thread as the DependencyObject_
```_ 

This error occur irregularly  in about 10 seconds . 
Pls help.

**Comment by mesta1** [comment]
This should be fixed now. Strange that I couldn't reproduce it before with my previous camera.
