### ISSUE TITLE
GPL instead of MIT licence

### ISSUE THREAD

**Issue by bbenno** [mesta1/Recording-video-with-c-#6]
Using FFMPEG via [Accord.Video.FFMPEG](https://www.nuget.org/packages/Accord.Video.FFMPEG/) (both GPL only) requires you to publish your derived work also under the GPL license.

**Comment by mesta1** [comment]
FFMPEG has both a GPL and a LGPL version. Accord licensing page is this one: http://accord-framework.net/license.html and they state it is a LGPL license.

**Comment by bbenno** [comment]
All right then.
I just though of that because the website states 
> [....]using FFMPEG. For this reason, this package [meaning Accord.Video.FFMPEG] is available under the GPL license only. [[source](https://www.nuget.org/packages/Accord.Video.FFMPEG/)]

Also the license url (http://accord-framework.net/gpl.txt) made me think that it it is GPL, not LGPL.

**Comment by mesta1** [comment]
Yes it is definetely possible that they are using the GPL dll. I will update the license.

**Comment by mesta1** [comment]
About the GPL and LGPL issue, here are a couple of links 

http://www.aforgenet.com/forum/viewtopic.php?f=7&t=2963

https://archive.codeplex.com/?p=aforgeffmpeg
